### ISSUE TITLE
2 quick questions

### ISSUE THREAD

**Issue by cvega** [jenkinsci/service-fabric-plugin#13]
I have two hopefully quick questions.

- do you intend to support pipeline?
- is this linux specific?

Thanks for your time.

**Comment by ArieShout** [comment]
Pipeline support was addressed in #6 

It should be working on Windows as long as you have ported version of Shell (`sh.exe`) in your path.

**Comment by cvega** [comment]
@ArieShout Thanks for the response. This is exactly what I was looking for.
