### ISSUE TITLE
Incompatible comparator used in the generated deploy script

### ISSUE THREAD

**Issue by ArieShout** [jenkinsci/service-fabric-plugin#7]
In the deploy script generated by `SFCommandBuilder` we're using `==` for equality comparison. However, this is not compatible in some `sh` implementation.

In Ubuntu 16.04, we'll get the following error while deploying a Service Fabric application using the plugin:

```
+ [ 1 == 1 ]
/tmp/jenkins4402809931963813129.sh: 2: [: 1: unexpected operator
```

We should use `=` instead.

**Comment by rapatchi** [comment]
Hi,

Thanks for pointing it out fixed it in this commit #10
